name: .NET

on:
  push:
    branches: [ master ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
      
    - name: Docker Build and Push
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          ferzim/conversao-peso-semanak8s:latest
          ferzim/conversao-peso-semanak8s:${{ github.run_number }}
